# CRMEB 相关配置
crmeb:
  version: CRMEB-JAVA-KY-v1.3.4 # 当前代码版本
  imagePath: crmeb\crmebimage\

server:
  #  port: 443
  port: 8443
#  ssl:
#    key-store: classpath:httpsKey.p12 #表示密钥文件名
#    key-alias: tomcathttps #表示密钥别名
#    key-store-password: 123456 #就是在cmd命令执行过程中输入的密码

spring:
  profiles:
    #  配置的环境
    active: prod
    #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.80.138:3306/db_duomai?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
    username: duomai
    password: ZN5SCWdZbXAi7A5t
  redis:
    host: 43.138.80.138 #地址
    port: 6379 #端口
    password: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 3 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
